import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Main_Provider from "@/providers/providers";
import Main_Layout from "@/components/layouts/main-layout";

const InterFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${InterFont.variable} antialiased`}>
        <Main_Provider>
          <Main_Layout>{children}</Main_Layout>
        </Main_Provider>
      </body>
    </html>
  );
}
